"""Add par for course

Revision ID: 22a115a62523
Revises: f157fcb1dcb4
Create Date: 2025-05-20 13:34:55.598015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '22a115a62523'
down_revision: Union[str, None] = 'f157fcb1dcb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('courses', sa.Column('total_par', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'total_par')
    # ### end Alembic commands ###
