"""Update email and phone

Revision ID: 5e705cc85e30
Revises: f0ab5ad0be84
Create Date: 2025-06-07 20:31:18.619060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e705cc85e30'
down_revision: Union[str, None] = 'f0ab5ad0be84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'email',
                    existing_type=sa.String(100),
                    nullable=True)
    op.add_column('players', sa.Column('phone', sa.VARCHAR(100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'email',
                    existing_type=sa.String(),
                    nullable=False)
    op.drop_column('players', 'phone')
    # ### end Alembic commands ###
