"""Add new fields

Revision ID: 727942d4bead
Revises: 21ac451c434a
Create Date: 2025-06-21 09:29:01.102925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '727942d4bead'
down_revision: Union[str, None] = '21ac451c434a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_flights', sa.Column('min_score', sa.Integer(), nullable=True))
    op.add_column('tournament_flights', sa.Column('max_score', sa.Integer(), nullable=True))
    op.add_column('tournament_scores', sa.Column('player_id', sa.Integer(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
