"""Initial migration

Revision ID: 88661b4a16f9
Revises: 
Create Date: 2025-04-20 12:17:21.956436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88661b4a16f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.drop_column('teams', 'date_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('date_created', sa.DATE(), nullable=True))
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_column('teams', 'created_at')
    # ### end Alembic commands ###
