"""Add tournament tables

Revision ID: cb6e841616fb
Revises: 22a115a62523
Create Date: 2025-05-27 17:56:21.941764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb6e841616fb'
down_revision: Union[str, None] = '22a115a62523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('format', sa.String(length=100), nullable=False),
    sa.Column('scoring_type', sa.String(length=100), nullable=False),
    sa.Column('number_of_days', sa.Integer(), nullable=True),
    sa.Column('use_flights', sa.Boolean(), nullable=True),
    sa.Column('number_of_flights', sa.Integer(), nullable=True),
    sa.Column('handicap_allowance', sa.Integer(), nullable=True),
    sa.Column('participant_type', sa.Enum('INDIVIDUAL', 'TEAM', 'MIXED', name='participanttype'), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    op.create_table('tournament_course',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tournament_id', 'course_id')
    )
    op.create_table('tournament_flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('min_handicap', sa.Float(), nullable=True),
    sa.Column('max_handicap', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_flights_id'), 'tournament_flights', ['id'], unique=False)
    op.create_table('tournament_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_rounds_id'), 'tournament_rounds', ['id'], unique=False)
    op.create_table('tournament_team',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tournament_id', 'team_id')
    )
    op.create_table('tournament_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['tournament_flights.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_participants_id'), 'tournament_participants', ['id'], unique=False)
    op.create_table('tournament_team_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('hole_number', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['tournament_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_team_scores_id'), 'tournament_team_scores', ['id'], unique=False)
    op.create_table('tournament_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('hole_number', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['tournament_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['tournament_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_scores_id'), 'tournament_scores', ['id'], unique=False)
    op.drop_index('_match_team_player_uc', table_name='match_players')
    op.drop_index('ix_match_players_id', table_name='match_players')
    op.drop_table('match_players')
    op.drop_column('courses', 'date_created')
    op.alter_column('holes', 'handicap',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournament_scores_id'), table_name='tournament_scores')
    op.drop_table('tournament_scores')
    op.drop_index(op.f('ix_tournament_team_scores_id'), table_name='tournament_team_scores')
    op.drop_table('tournament_team_scores')
    op.drop_index(op.f('ix_tournament_participants_id'), table_name='tournament_participants')
    op.drop_table('tournament_participants')
    op.drop_table('tournament_team')
    op.drop_index(op.f('ix_tournament_rounds_id'), table_name='tournament_rounds')
    op.drop_table('tournament_rounds')
    op.drop_index(op.f('ix_tournament_flights_id'), table_name='tournament_flights')
    op.drop_table('tournament_flights')
    op.drop_table('tournament_course')
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
