"""Add tournament scores

Revision ID: d7c0c6d17106
Revises: f7921b29071d
Create Date: 2025-06-22 12:38:05.501131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd7c0c6d17106'
down_revision: Union[str, None] = 'f7921b29071d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_scores', sa.Column('tournament_id', sa.Integer(), nullable=True))
    op.add_column('tournament_scores', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('tournament_scores', sa.Column('total_strokes', sa.Integer(), nullable=True))
    op.drop_constraint('tournament_scores_ibfk_2', 'tournament_scores', type_='foreignkey')
    op.create_foreign_key(None, 'tournament_scores', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tournament_scores', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tournament_scores', 'tournament_players', ['player_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tournament_scores', 'hole_number')
    op.drop_column('tournament_scores', 'score')
    op.drop_column('tournament_scores', 'participant_id')
    op.create_foreign_key(None, 'tournament_team', 'tournament_flights', ['flight_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
