"""Add new league settings

Revision ID: f157fcb1dcb4
Revises: 1003cce04552
Create Date: 2025-05-20 13:16:12.296459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f157fcb1dcb4'
down_revision: Union[str, None] = '1003cce04552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('leagues', sa.Column('handicap_required_scores', sa.Integer(), nullable=True))
    op.add_column('leagues', sa.Column('handicap_recent_scores_used', sa.Integer(), nullable=True))
    op.add_column('leagues', sa.Column('handicap_perecentage_to_par', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'handicap_perecentage_to_par')
    op.drop_column('leagues', 'handicap_recent_scores_used')
    op.drop_column('leagues', 'handicap_required_scores')
    # ### end Alembic commands ###
